repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
- repo: local
  hooks:
  - id: cargo-format
    name: Check cargo fmt
    entry: cargo fmt
    language: system
    types: [rust]
    pass_filenames: false
