[package]
name = "sarcastic-messages"
version = "0.1.0"
authors = ["Daniel Chabrowski <danchabrowski@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.147", features = [ "derive" ] }
uuid = { version = "1.2.2", features = [ "v4", "serde" ] }
