[package]
name = "sarcastic-audio-sink"
version = "0.1.0"
authors = ["Daniel Chabrowski <danchabrowski@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
env_logger = "0.8"
futures-util = "0.3"
glib = "0.10"
gstreamer = "0.16"
gstreamer-player = "0.16"
log = "0.4"
pulse = { version = "2", package = "libpulse-binding" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tokio = { version = "1", features = [ "full" ] }
tokio-tungstenite = "0.13"
url = "2"
uuid = { version = "0.8", features = [ "v4" ] }
