[package]
name = "sarcastic-audio-sink"
version = "0.1.0"
authors = ["Daniel Chabrowski <danchabrowski@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
env_logger = "0.9.0"
futures-util = "0.3.17"
glib = "0.14.8"
gstreamer = "0.17.4"
gstreamer-player = "0.17.0"
log = "0.4.14"
messages = { package = "sarcastic-messages", version = "0.1", path = "../messages" }
pulse = { version = "2.25.0", package = "libpulse-binding" }
serde = { version = "1.0.130", features = [ "derive" ] }
serde_json = "1.0.68"
tokio = { version = "1.12.0", features = [ "full" ] }
tokio-tungstenite = "0.15.0"
url = "2.2.2"
uuid = { version = "0.8.2", features = [ "v4" ] }
