[package]
name = "sarcastic-audio-sink"
version = "0.1.0"
authors = ["Daniel Chabrowski <danchabrowski@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.8"
pulse = { version = "2", package = "libpulse-binding" }
tokio = { version = "1", features = [ "full" ]}
tokio-tungstenite = "0.13"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
gstreamer = "0.16"
gstreamer-audio = "0.16"
futures-util = "0.3"
uuid = { version = "0.8", features = [ "v4" ] }
url = "2"
